# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-23 16:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('timestamp', models.TimeField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('nationality', models.CharField(blank=True, max_length=100)),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('created', models.DateField(blank=True, null=True)),
                ('script', models.TextField(blank=True)),
                ('mp3_en', models.FileField(blank=True, null=True, upload_to=b'items')),
                ('mp3_gr', models.FileField(blank=True, null=True, upload_to=b'items')),
                ('source_thumb', models.FileField(blank=True, null=True, upload_to=b'items_thumb')),
                ('photo1', models.FileField(blank=True, null=True, upload_to=b'items')),
                ('photo2', models.FileField(blank=True, null=True, upload_to=b'items')),
                ('photo3', models.FileField(blank=True, null=True, upload_to=b'items')),
                ('photo4', models.FileField(blank=True, null=True, upload_to=b'items')),
                ('photo5', models.FileField(blank=True, null=True, upload_to=b'items')),
                ('photo6', models.FileField(blank=True, null=True, upload_to=b'items')),
                ('photo7', models.FileField(blank=True, null=True, upload_to=b'items')),
                ('photo8', models.FileField(blank=True, null=True, upload_to=b'items')),
                ('photo9', models.FileField(blank=True, null=True, upload_to=b'items')),
                ('photo10', models.FileField(blank=True, null=True, upload_to=b'items')),
            ],
            options={
                'ordering': ['timestamp', 'name'],
            },
        ),
    ]
