# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-01 13:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0002_auto_20160328_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='sex',
            field=models.CharField(choices=[(b'Male', b'Male'), (b'Female', b'Female')], default=b'm', max_length=10),
        ),
    ]
