# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-02 12:02
from __future__ import unicode_literals

from django.db import migrations


def mv_sex(apps, schema_editor):
    Person = apps.get_model("interviews", "Item")
    for person in Person.objects.all():
        if person.sex == 'm':
            person.sex = 'Male'
        else:
            person.sex = 'Female'
        person.save()


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0003_auto_20160401_1314'),
    ]

    operations = [
        migrations.RunPython(mv_sex),
    ]
