# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-25 18:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_auto_20160108_2005'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='created',
            field=models.DateField(blank=True, null=True),
        ),
    ]
