# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-25 18:22
from __future__ import unicode_literals
from datetime import datetime

from django.db import migrations


def mv_graffiti_years(apps, schema_editor):
    Item = apps.get_model("gallery", "Item")
    for item in Item.objects.all():
        if item.year:
            item.created = datetime.strptime(str(item.year), '%Y')
            item.save()


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_item_created'),
    ]

    operations = [
        migrations.RunPython(mv_graffiti_years),
    ]
