# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-11 13:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0007_item_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='pick_date',
            field=models.CharField(choices=[(b'Full', b'Full'), (b'YearMonth', b'YearMonth'), (b'Year', b'Year')], default=b'Full', max_length=10),
        ),
    ]
