# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-11 15:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0008_item_pick_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['created', 'timestamp', 'title']},
        ),
    ]
