# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-26 13:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0010_uploadeditem'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadeditem',
            name='processed',
            field=models.BooleanField(default=False),
        ),
    ]
