# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-26 13:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0011_uploadeditem_processed'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadeditem',
            name='source_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='uploadeditem',
            name='url',
            field=models.URLField(blank=True),
        ),
    ]
